#server:
#  port: 8301

spring:
  application:
    # 同一服务多实例模拟,服务名得一致,负载均衡才能看到效果
    name: beter-spring-cloud-producer-user
  main:
    # 允许定义相同的bean对象 去覆盖原有的
    allow-bean-definition-overriding: true
############zipkin相关###########
  zipkin:
    base-url: http://localhost:9411
    # 让nacos把它当成一个URL，而不要当做服务名
    # discovery-client-enabled: false
  sleuth:
    sampler:
      # 采用率值介于：0到1，1表示全部采集，默认的采样比例为: 0.1(即10%)。
      probability: 1
############zipkin相关###########


#####################################################eureka相关###############################################################
eureka:
  client:
    service-url:
      # 指定当前Client所要连接的eureka Server
      defaultZone: http://localhost:8001/eureka
      registry-fetch-interval-seconds: 5 # 抓取服务列表
  instance:
    prefer-ip-address: true
    # instance-id: beter-spring-cloud-producer-user
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    # 设置当前Client每1秒向Server发送一次心跳，单位秒, 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 5
    # 指定让Server认定当前Client已经失效的时间，将来可以从注册表中剔除了，单位秒,续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 10

# 注册到eureka时，点进去的一些信息
info:
  version: beter-spring-cloud-producer-user(from server)
  app.auth: beter
  app.name: zbt
  company.name: www.baidu.com
  company.addr: 浙江省杭州市
#####################################################eureka相关###############################################################


#####################################################feign相关###############################################################
# https://developer.51cto.com/article/709758.html
feign:
  client:
    config:
      default:
        connectTimeout: 5000   # 指定Feign客户端连接提供者的超时时限
        readTimeout: 5000      # 指定Feign客户端连接上提供者后，向提供者进行提交请求，从提交时刻开始，到接收到响应，这个时段的超时时限(发出到接收到信息的时间)
        loggerLevel: basic
  #请求和响应GZIP压缩支持
  compression:
    request:
      enabled: true
      #支持压缩的mime types
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

  # 开启Feign对Hystrix的支持
  hystrix:
    enabled: true
#####################################################feign相关###############################################################


# 调用http://localhost:port/actuator/service-registry  下线参数{"status":"DOWN"}  上线参数{"status":"UP"}
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,hystrix.stream,service-registry,refresh,bus-refresh
  # 开启shutdown监控终端
  endpoint:
    shutdown:
      enabled: true